# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 16:49
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
