# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_author',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Portfolio', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=pyuploadcare.dj.models.ImageField(default='https://unsplash.it/1200/768.jpg?image=1008'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default='nim', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
