# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200608_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_author',
            new_name='user',
        ),
    ]
